{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Carpenters"], "artist_links": ["/wiki/The_Carpenters"], "is_winner": true, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Gladys Knight & the Pips"], "artist_links": ["/wiki/Gladys_Knight_%26_the_Pips"], "is_winner": false, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Tony Orlando and Dawn"], "artist_links": ["/wiki/Tony_Orlando_and_Dawn"], "is_winner": false, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Gladys Knight & the Pips"], "artist_links": ["/wiki/Gladys_Knight_%26_the_Pips"], "is_winner": true, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bachman\u2013Turner Overdrive"], "artist_links": ["/wiki/Bachman%E2%80%93Turner_Overdrive"], "is_winner": false, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Wings"], "artist_links": ["/wiki/Wings_(band)"], "is_winner": false, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Tony Orlando and Dawn"], "artist_links": ["/wiki/Tony_Orlando_and_Dawn"], "is_winner": true, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": false, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Earth, Wind & Fire"], "artist_links": ["/wiki/Earth,_Wind_%26_Fire"], "is_winner": false, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Chicago"], "artist_links": ["/wiki/Chicago_(band)"], "is_winner": true, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": false, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Earth, Wind & Fire"], "artist_links": ["/wiki/Earth,_Wind_%26_Fire"], "is_winner": false, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fleetwood Mac"], "artist_links": ["/wiki/Fleetwood_Mac"], "is_winner": true, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": false, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["KC and the Sunshine Band"], "artist_links": ["/wiki/KC_and_the_Sunshine_Band"], "is_winner": false, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bee Gees"], "artist_links": ["/wiki/Bee_Gees"], "is_winner": true, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fleetwood Mac"], "artist_links": ["/wiki/Fleetwood_Mac"], "is_winner": false, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Foreigner"], "artist_links": ["/wiki/Foreigner_(band)"], "is_winner": false, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bee Gees"], "artist_links": ["/wiki/Bee_Gees"], "is_winner": true, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Cheap Trick"], "artist_links": ["/wiki/Cheap_Trick"], "is_winner": false, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Supertramp"], "artist_links": ["/wiki/Supertramp"], "is_winner": false, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": true, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Queen"], "artist_links": ["/wiki/Queen_(band)"], "is_winner": false, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Rolling Stones"], "artist_links": ["/wiki/The_Rolling_Stones"], "is_winner": false, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Air Supply"], "artist_links": ["/wiki/Air_Supply"], "is_winner": true, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["AC/DC"], "artist_links": ["/wiki/AC/DC"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Pointer Sisters"], "artist_links": ["/wiki/The_Pointer_Sisters"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["REO Speedwagon"], "artist_links": ["/wiki/REO_Speedwagon"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Hall & Oates"], "artist_links": ["/wiki/Hall_%26_Oates"], "is_winner": true, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fleetwood Mac"], "artist_links": ["/wiki/Fleetwood_Mac"], "is_winner": false, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The J. Geils Band"], "artist_links": ["/wiki/The_J._Geils_Band"], "is_winner": false, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Hall & Oates"], "artist_links": ["/wiki/Hall_%26_Oates"], "is_winner": true, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Def Leppard"], "artist_links": ["/wiki/Def_Leppard"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Men at Work"], "artist_links": ["/wiki/Men_at_Work"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Police"], "artist_links": ["/wiki/The_Police"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Hall & Oates"], "artist_links": ["/wiki/Hall_%26_Oates"], "is_winner": true, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Huey Lewis and the News"], "artist_links": ["/wiki/Huey_Lewis_and_the_News"], "is_winner": false, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Van Halen"], "artist_links": ["/wiki/Van_Halen"], "is_winner": false, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Chicago"], "artist_links": ["/wiki/Chicago_(band)"], "is_winner": true, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Kool & the Gang"], "artist_links": ["/wiki/Kool_%26_the_Gang"], "is_winner": false, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Tears for Fears"], "artist_links": ["/wiki/Tears_for_Fears"], "is_winner": false, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Huey Lewis and the News"], "artist_links": ["/wiki/Huey_Lewis_and_the_News"], "is_winner": true, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Genesis"], "artist_links": ["/wiki/Genesis_(band)"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Heart"], "artist_links": ["/wiki/Heart_(band)"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Van Halen"], "artist_links": ["/wiki/Van_Halen"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bon Jovi"], "artist_links": ["/wiki/Bon_Jovi"], "is_winner": true, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Lisa Lisa and Cult Jam"], "artist_links": ["/wiki/Lisa_Lisa_and_Cult_Jam"], "is_winner": false, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["U2"], "artist_links": ["/wiki/U2"], "is_winner": false, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Gloria Estefan", "Miami Sound Machine"], "artist_links": ["/wiki/Gloria_Estefan", "/wiki/Miami_Sound_Machine"], "is_winner": true, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Def Leppard"], "artist_links": ["/wiki/Def_Leppard"], "is_winner": false, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Van Halen"], "artist_links": ["/wiki/Van_Halen"], "is_winner": false, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["New Kids on the Block"], "artist_links": ["/wiki/New_Kids_on_the_Block"], "is_winner": true, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bon Jovi"], "artist_links": ["/wiki/Bon_Jovi"], "is_winner": false, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Milli Vanilli"], "artist_links": ["/wiki/Milli_Vanilli"], "is_winner": false, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Aerosmith"], "artist_links": ["/wiki/Aerosmith"], "is_winner": true, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Bell Biv DeVoe"], "artist_links": ["/wiki/Bell_Biv_DeVoe"], "is_winner": false, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["New Kids on the Block"], "artist_links": ["/wiki/New_Kids_on_the_Block"], "is_winner": false, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["C+C Music Factory"], "artist_links": ["/wiki/C%2BC_Music_Factory"], "is_winner": true, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Color Me Badd"], "artist_links": ["/wiki/Color_Me_Badd"], "is_winner": false, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Guns N' Roses"], "artist_links": ["/wiki/Guns_N%27_Roses"], "is_winner": false, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Genesis"], "artist_links": ["/wiki/Genesis_(band)"], "is_winner": true, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Kris Kross"], "artist_links": ["/wiki/Kris_Kross"], "is_winner": false, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["U2"], "artist_links": ["/wiki/U2"], "is_winner": false, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Aerosmith"], "artist_links": ["/wiki/Aerosmith"], "is_winner": true, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Pearl Jam"], "artist_links": ["/wiki/Pearl_Jam"], "is_winner": false, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["U2"], "artist_links": ["/wiki/U2"], "is_winner": false, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Ace of Base"], "artist_links": ["/wiki/Ace_of_Base"], "is_winner": true, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Pink Floyd"], "artist_links": ["/wiki/Pink_Floyd"], "is_winner": false, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Stone Temple Pilots"], "artist_links": ["/wiki/Stone_Temple_Pilots"], "is_winner": false, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": true, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Boyz II Men"], "artist_links": ["/wiki/Boyz_II_Men"], "is_winner": false, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Hootie & the Blowfish"], "artist_links": ["/wiki/Hootie_%26_the_Blowfish"], "is_winner": false, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Hootie & the Blowfish"], "artist_links": ["/wiki/Hootie_%26_the_Blowfish"], "is_winner": true, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Dave Matthews Band"], "artist_links": ["/wiki/Dave_Matthews_Band"], "is_winner": false, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fugees"], "artist_links": ["/wiki/Fugees"], "is_winner": false, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Spice Girls"], "artist_links": ["/wiki/Spice_Girls"], "is_winner": true, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["U2"], "artist_links": ["/wiki/U2"], "is_winner": false, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Wallflowers"], "artist_links": ["/wiki/The_Wallflowers"], "is_winner": false, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Aerosmith"], "artist_links": ["/wiki/Aerosmith"], "is_winner": true, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Backstreet Boys"], "artist_links": ["/wiki/Backstreet_Boys"], "is_winner": false, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Matchbox Twenty"], "artist_links": ["/wiki/Matchbox_Twenty"], "is_winner": false, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Backstreet Boys"], "artist_links": ["/wiki/Backstreet_Boys"], "is_winner": true, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["NSYNC"], "artist_links": ["/wiki/NSYNC"], "is_winner": false, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Santana"], "artist_links": ["/wiki/Santana_(band)"], "is_winner": false, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Backstreet Boys"], "artist_links": ["/wiki/Backstreet_Boys"], "is_winner": true, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Creed"], "artist_links": ["/wiki/Creed_(band)"], "is_winner": false, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["NSYNC"], "artist_links": ["/wiki/NSYNC"], "is_winner": false, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["NSYNC"], "artist_links": ["/wiki/NSYNC"], "is_winner": true, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Dave Matthews Band"], "artist_links": ["/wiki/Dave_Matthews_Band"], "is_winner": false, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["U2"], "artist_links": ["/wiki/U2"], "is_winner": false, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Creed"], "artist_links": ["/wiki/Creed_(band)"], "is_winner": true, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Linkin Park"], "artist_links": ["/wiki/Linkin_Park"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Nickelback"], "artist_links": ["/wiki/Nickelback"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fleetwood Mac"], "artist_links": ["/wiki/Fleetwood_Mac"], "is_winner": true, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["3 Doors Down"], "artist_links": ["/wiki/3_Doors_Down"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Matchbox Twenty"], "artist_links": ["/wiki/Matchbox_Twenty"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Outkast"], "artist_links": ["/wiki/Outkast"], "is_winner": true, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Evanescence"], "artist_links": ["/wiki/Evanescence"], "is_winner": false, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Nickelback"], "artist_links": ["/wiki/Nickelback"], "is_winner": false, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Black Eyed Peas"], "artist_links": ["/wiki/The_Black_Eyed_Peas"], "is_winner": true, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["3 Doors Down"], "artist_links": ["/wiki/3_Doors_Down"], "is_winner": false, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Green Day"], "artist_links": ["/wiki/Green_Day"], "is_winner": false, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Red Hot Chili Peppers"], "artist_links": ["/wiki/Red_Hot_Chili_Peppers"], "is_winner": true, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Nickelback"], "artist_links": ["/wiki/Nickelback"], "is_winner": false, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Pussycat Dolls"], "artist_links": ["/wiki/The_Pussycat_Dolls"], "is_winner": false, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Nickelback"], "artist_links": ["/wiki/Nickelback"], "is_winner": true, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Linkin Park"], "artist_links": ["/wiki/Linkin_Park"], "is_winner": false, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": false, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Daughtry"], "artist_links": ["/wiki/Daughtry_(band)"], "is_winner": true, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Coldplay"], "artist_links": ["/wiki/Coldplay"], "is_winner": false, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Eagles"], "artist_links": ["/wiki/Eagles_(band)"], "is_winner": false, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Black Eyed Peas"], "artist_links": ["/wiki/The_Black_Eyed_Peas"], "is_winner": true, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Kings of Leon"], "artist_links": ["/wiki/Kings_of_Leon"], "is_winner": false, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Nickelback"], "artist_links": ["/wiki/Nickelback"], "is_winner": false, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Black Eyed Peas"], "artist_links": ["/wiki/The_Black_Eyed_Peas"], "is_winner": true, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": false, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Train"], "artist_links": ["/wiki/Train_(band)"], "is_winner": false, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": true, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["LMFAO"], "artist_links": ["/wiki/LMFAO"], "is_winner": false, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["OneRepublic"], "artist_links": ["/wiki/OneRepublic"], "is_winner": false, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": true, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Fun"], "artist_links": ["/wiki/Fun_(band)"], "is_winner": false, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["One Direction"], "artist_links": ["/wiki/One_Direction"], "is_winner": false, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Wanted"], "artist_links": ["/wiki/The_Wanted"], "is_winner": false, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["One Direction"], "artist_links": ["/wiki/One_Direction"], "is_winner": true, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Imagine Dragons"], "artist_links": ["/wiki/Imagine_Dragons"], "is_winner": false, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Macklemore & Ryan Lewis"], "artist_links": ["/wiki/Macklemore_%26_Ryan_Lewis"], "is_winner": false, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["One Direction"], "artist_links": ["/wiki/One_Direction"], "is_winner": true, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Imagine Dragons"], "artist_links": ["/wiki/Imagine_Dragons"], "is_winner": false, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["OneRepublic"], "artist_links": ["/wiki/OneRepublic"], "is_winner": false, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["One Direction"], "artist_links": ["/wiki/One_Direction"], "is_winner": true, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": false, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Walk the Moon"], "artist_links": ["/wiki/Walk_the_Moon"], "is_winner": false, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Twenty One Pilots"], "artist_links": ["/wiki/Twenty_One_Pilots"], "is_winner": true, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Chainsmokers"], "artist_links": ["/wiki/The_Chainsmokers"], "is_winner": false, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["DNCE"], "artist_links": ["/wiki/DNCE"], "is_winner": false, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Imagine Dragons"], "artist_links": ["/wiki/Imagine_Dragons"], "is_winner": true, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["The Chainsmokers"], "artist_links": ["/wiki/The_Chainsmokers"], "is_winner": false, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Coldplay"], "artist_links": ["/wiki/Coldplay"], "is_winner": false, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Migos"], "artist_links": ["/wiki/Migos"], "is_winner": true, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Imagine Dragons"], "artist_links": ["/wiki/Imagine_Dragons"], "is_winner": false, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": false, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["BTS"], "artist_links": ["/wiki/BTS"], "is_winner": true, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Jonas Brothers"], "artist_links": ["/wiki/Jonas_Brothers"], "is_winner": false, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Panic! at the Disco"], "artist_links": ["/wiki/Panic!_at_the_Disco"], "is_winner": false, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["BTS"], "artist_links": ["/wiki/BTS"], "is_winner": false, "year": "2020"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Jonas Brothers"], "artist_links": ["/wiki/Jonas_Brothers"], "is_winner": false, "year": "2020"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Pop/Rock_Band/Duo/Group", "artists": ["Maroon 5"], "artist_links": ["/wiki/Maroon_5"], "is_winner": false, "year": "2020"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Carter Family"], "artist_links": ["/wiki/Carter_Family"], "is_winner": true, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Osborne Brothers"], "artist_links": ["/wiki/The_Osborne_Brothers"], "is_winner": false, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1974", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1974"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Conway Twitty", "Loretta Lynn"], "artist_links": ["/wiki/Conway_Twitty", "/wiki/Loretta_Lynn"], "is_winner": true, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["George Jones", "Tammy Wynette"], "artist_links": ["/wiki/George_Jones", "/wiki/Tammy_Wynette"], "is_winner": false, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1975", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1975"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Donny Osmond", "Marie Osmond"], "artist_links": ["/wiki/Donny_Osmond", "/wiki/Marie_Osmond"], "is_winner": true, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1976", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Conway Twitty", "Loretta Lynn"], "artist_links": ["/wiki/Conway_Twitty", "/wiki/Loretta_Lynn"], "is_winner": false, "year": "1976"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Conway Twitty", "Loretta Lynn"], "artist_links": ["/wiki/Conway_Twitty", "/wiki/Loretta_Lynn"], "is_winner": true, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["George Jones", "Tammy Wynette"], "artist_links": ["/wiki/George_Jones", "/wiki/Tammy_Wynette"], "is_winner": false, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1977", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1977"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Conway Twitty", "Loretta Lynn"], "artist_links": ["/wiki/Conway_Twitty", "/wiki/Loretta_Lynn"], "is_winner": true, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["George Jones", "Tammy Wynette"], "artist_links": ["/wiki/George_Jones", "/wiki/Tammy_Wynette"], "is_winner": false, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1978", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1978"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": true, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Waylon Jennings", "Willie Nelson"], "artist_links": ["/wiki/Waylon_Jennings", "/wiki/Willie_Nelson"], "is_winner": false, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1979", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1979"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": true, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1980", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Kenny Rogers", "Dottie West"], "artist_links": ["/wiki/Kenny_Rogers", "/wiki/Dottie_West"], "is_winner": false, "year": "1980"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": true, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Charlie Daniels Band"], "artist_links": ["/wiki/Charlie_Daniels_Band"], "is_winner": false, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1981", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1981"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": true, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Willie Nelson", "Ray Price"], "artist_links": ["/wiki/Willie_Nelson", "/wiki/Ray_Price_(musician)"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1982", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1982"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1983", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1983"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Kenny Rogers", "Dolly Parton"], "artist_links": ["/wiki/Kenny_Rogers", "/wiki/Dolly_Parton"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1984", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1984"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1985", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Statler Brothers"], "artist_links": ["/wiki/The_Statler_Brothers"], "is_winner": false, "year": "1985"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1986", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1986"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Forester Sisters"], "artist_links": ["/wiki/The_Forester_Sisters"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1987", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Marie Osmond", "Paul Davis"], "artist_links": ["/wiki/Marie_Osmond", "/wiki/Paul_Davis_(singer)"], "is_winner": false, "year": "1987"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1988", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Restless Heart"], "artist_links": ["/wiki/Restless_Heart"], "is_winner": false, "year": "1988"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1989", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Oak Ridge Boys"], "artist_links": ["/wiki/The_Oak_Ridge_Boys"], "is_winner": false, "year": "1989"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Highway 101"], "artist_links": ["/wiki/Highway_101_(band)"], "is_winner": false, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1990", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1990"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1991", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Shenandoah"], "artist_links": ["/wiki/Shenandoah_(band)"], "is_winner": false, "year": "1991"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Judds"], "artist_links": ["/wiki/The_Judds"], "is_winner": false, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1992", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Kentucky Headhunters"], "artist_links": ["/wiki/The_Kentucky_Headhunters"], "is_winner": false, "year": "1992"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1993", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Sawyer Brown"], "artist_links": ["/wiki/Sawyer_Brown"], "is_winner": false, "year": "1993"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1994", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Little Texas"], "artist_links": ["/wiki/Little_Texas_(band)"], "is_winner": false, "year": "1994"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1995", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Little Texas"], "artist_links": ["/wiki/Little_Texas_(band)"], "is_winner": false, "year": "1995"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["BlackHawk"], "artist_links": ["/wiki/BlackHawk_(band)"], "is_winner": false, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1996", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1996"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": true, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["BlackHawk"], "artist_links": ["/wiki/BlackHawk_(band)"], "is_winner": false, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1997", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Mavericks"], "artist_links": ["/wiki/The_Mavericks"], "is_winner": false, "year": "1997"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1998", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Sawyer Brown"], "artist_links": ["/wiki/Sawyer_Brown"], "is_winner": false, "year": "1998"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-1999", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dixie Chicks"], "artist_links": ["/wiki/Dixie_Chicks"], "is_winner": false, "year": "1999"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": true, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Diamond Rio"], "artist_links": ["/wiki/Diamond_Rio"], "is_winner": false, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2000", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dixie Chicks"], "artist_links": ["/wiki/Dixie_Chicks"], "is_winner": false, "year": "2000"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dixie Chicks"], "artist_links": ["/wiki/Dixie_Chicks"], "is_winner": true, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2001", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lonestar"], "artist_links": ["/wiki/Lonestar"], "is_winner": false, "year": "2001"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": true, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lonestar"], "artist_links": ["/wiki/Lonestar"], "is_winner": false, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2002", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["SheDaisy"], "artist_links": ["/wiki/SheDaisy"], "is_winner": false, "year": "2002"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dixie Chicks"], "artist_links": ["/wiki/Dixie_Chicks"], "is_winner": true, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lonestar"], "artist_links": ["/wiki/Lonestar"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Alabama"], "artist_links": ["/wiki/Alabama_(American_band)"], "is_winner": true, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2003", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dixie Chicks"], "artist_links": ["/wiki/Dixie_Chicks"], "is_winner": false, "year": "2003"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": true, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lonestar"], "artist_links": ["/wiki/Lonestar"], "is_winner": false, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2004", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": false, "year": "2004"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": true, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Big & Rich"], "artist_links": ["/wiki/Big_%26_Rich"], "is_winner": false, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2005", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": false, "year": "2005"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": true, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2006", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Montgomery Gentry"], "artist_links": ["/wiki/Montgomery_Gentry"], "is_winner": false, "year": "2006"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": true, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Big & Rich"], "artist_links": ["/wiki/Big_%26_Rich"], "is_winner": false, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2007", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2007"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": true, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Brooks & Dunn"], "artist_links": ["/wiki/Brooks_%26_Dunn"], "is_winner": false, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2008", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Sugarland"], "artist_links": ["/wiki/Sugarland"], "is_winner": false, "year": "2008"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": true, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Sugarland"], "artist_links": ["/wiki/Sugarland"], "is_winner": false, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2009", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2009"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": true, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": false, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2010", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2010"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": true, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Band Perry"], "artist_links": ["/wiki/The_Band_Perry"], "is_winner": false, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2011", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2011"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": true, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Rascal Flatts"], "artist_links": ["/wiki/Rascal_Flatts"], "is_winner": false, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2012", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2012"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": true, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["The Band Perry"], "artist_links": ["/wiki/The_Band_Perry"], "is_winner": false, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2013", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": false, "year": "2013"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": true, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Eli Young Band"], "artist_links": ["/wiki/Eli_Young_Band"], "is_winner": false, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2014", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lady Antebellum"], "artist_links": ["/wiki/Lady_Antebellum"], "is_winner": false, "year": "2014"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": true, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Little Big Town"], "artist_links": ["/wiki/Little_Big_Town"], "is_winner": false, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2015", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2015"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": true, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Old Dominion"], "artist_links": ["/wiki/Old_Dominion_(band)"], "is_winner": false, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2016", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Zac Brown Band"], "artist_links": ["/wiki/Zac_Brown_Band"], "is_winner": false, "year": "2016"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Little Big Town"], "artist_links": ["/wiki/Little_Big_Town"], "is_winner": true, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": false, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2017", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Old Dominion"], "artist_links": ["/wiki/Old_Dominion_(band)"], "is_winner": false, "year": "2017"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": true, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dan + Shay"], "artist_links": ["/wiki/Dan_%2B_Shay"], "is_winner": false, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2018", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Lanco"], "artist_links": ["/wiki/Lanco_(band)"], "is_winner": false, "year": "2018"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dan + Shay"], "artist_links": ["/wiki/Dan_%2B_Shay"], "is_winner": true, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": false, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2019", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Old Dominion"], "artist_links": ["/wiki/Old_Dominion_(band)"], "is_winner": false, "year": "2019"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Dan + Shay"], "artist_links": ["/wiki/Dan_%2B_Shay"], "is_winner": false, "year": "2020"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Florida Georgia Line"], "artist_links": ["/wiki/Florida_Georgia_Line"], "is_winner": false, "year": "2020"}
{"key": "American_Music_Award-American_Music_Award_for_Favorite_Country_Band/Duo/Group-2020", "award_organization": "American_Music_Award", "award_classification": "American_Music_Award_for_Favorite_Country_Band/Duo/Group", "artists": ["Old Dominion"], "artist_links": ["/wiki/Old_Dominion_(band)"], "is_winner": false, "year": "2020"}
